Repository Team-SSOK/ssom-backend, pull requests merged in 2025-06, with the labels that each got.

#37 fix : issue dto 매칭 및 ci/cd 테스트
  src/main/java/kr/ssok/ssom/backend/domain/issue/service/Impl/IssueServiceImpl.java
  src/main/java/kr/ssok/ssom/backend/global/dto/GitHubWebhookSenderDto.java
Labels: enhancement

#42 feat: JsonParsing 로직 수정 (#27, SCRUM-205)
  src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertServiceImpl.java
Labels: duplicate

#46 feat: opensearch 알림 empty list에 대한 return 처리(#27, SCRUM-205)
  src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertServiceImpl.java
Labels: enhancement

#48 feat: 로그 목록 필터링 기능 추가
  src/main/java/kr/ssok/ssom/backend/domain/logging/controller/LoggingController.java
  src/main/java/kr/ssok/ssom/backend/domain/logging/service/Impl/LoggingServiceImpl.java
  src/main/java/kr/ssok/ssom/backend/domain/logging/service/LoggingService.java
Labels: enhancement

#50 feat: 로그 목록 조회 시 최신순으로 정렬
  src/main/java/kr/ssok/ssom/backend/domain/logging/service/Impl/LoggingServiceImpl.java
Labels: enhancement

#52 fix: SSE 구독 기능을 로그 서비스에서 가져오도록 수정
  src/main/java/kr/ssok/ssom/backend/domain/logging/controller/LoggingController.java
  src/main/java/kr/ssok/ssom/backend/domain/logging/service/Impl/LoggingServiceImpl.java
  src/main/java/kr/ssok/ssom/backend/domain/logging/service/LoggingService.java
Labels: bug

#54 feat : FCM 기능 구현 (#19, SCRUM-212)
  src/main/java/kr/ssok/ssom/backend/domain/alert/controller/AlertController.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/controller/fcm/FcmController.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertGrafanaRequestDto.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertIssueRequestDto.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertOpensearchRequestDto.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertRequestDto.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertResponseDto.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertSendRequestDto.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/dto/fcm/FcmRegisterRequestDto.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/entity/Alert.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertService.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertServiceImpl.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/service/fcm/FcmService.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/service/fcm/FcmServiceImpl.java
  src/main/java/kr/ssok/ssom/backend/global/client/FirebaseClient.java
  src/main/java/kr/ssok/ssom/backend/global/config/FirebaseConfig.java
  src/main/java/kr/ssok/ssom/backend/global/dto/FcmMessageRequestDto.java
Labels: enhancement

#55 refactor : OpenSearchConfig 하드코딩 된 부분 Config 값 사용하도록 수정
  src/main/java/kr/ssok/ssom/backend/global/config/OpenSearchConfig.java
Labels: bug, enhancement

#58 feat : llm issue 초안 작성 debugging용 log.info
  src/main/java/kr/ssok/ssom/backend/domain/issue/service/Impl/IssueServiceImpl.java
  src/main/java/kr/ssok/ssom/backend/domain/logging/controller/LoggingController.java
Labels: bug, enhancement

#60 feat : llm issue 초안 작성 debugging용 log.info / 예외조건 수정
  src/main/java/kr/ssok/ssom/backend/domain/issue/service/Impl/IssueServiceImpl.java
Labels: bug, enhancement

#61 feat : llm issue 초안 작성 response dto boolean -> Boolean
  src/main/java/kr/ssok/ssom/backend/domain/issue/service/Impl/IssueServiceImpl.java
  src/main/java/kr/ssok/ssom/backend/global/dto/LlmApiResponseDto.java
Labels: bug, enhancement

#63 merge : prod(AWS) 환경으로 배포 (06/05)
  src/main/java/kr/ssok/ssom/backend/domain/alert/controller/AlertController.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/controller/fcm/FcmController.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertGrafanaRequestDto.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertIssueRequestDto.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertOpensearchRequestDto.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertRequestDto.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertResponseDto.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertSendRequestDto.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/dto/fcm/FcmRegisterRequestDto.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/entity/Alert.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertService.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertServiceImpl.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/service/fcm/FcmService.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/service/fcm/FcmServiceImpl.java
  src/main/java/kr/ssok/ssom/backend/domain/issue/service/Impl/IssueServiceImpl.java
  src/main/java/kr/ssok/ssom/backend/domain/logging/controller/LoggingController.java
  src/main/java/kr/ssok/ssom/backend/domain/logging/dto/LogDataDto.java
  src/main/java/kr/ssok/ssom/backend/domain/logging/entity/LogSummary.java
  src/main/java/kr/ssok/ssom/backend/domain/logging/service/Impl/LoggingServiceImpl.java
  src/main/java/kr/ssok/ssom/backend/domain/logging/service/LoggingService.java
  src/main/java/kr/ssok/ssom/backend/global/client/FirebaseClient.java
  src/main/java/kr/ssok/ssom/backend/global/client/LlmServiceClient.java
  src/main/java/kr/ssok/ssom/backend/global/config/FeignConfig.java
  src/main/java/kr/ssok/ssom/backend/global/config/FirebaseConfig.java
  src/main/java/kr/ssok/ssom/backend/global/config/OpenSearchConfig.java
  src/main/java/kr/ssok/ssom/backend/global/dto/FcmMessageRequestDto.java
  src/main/java/kr/ssok/ssom/backend/global/dto/LlmApiRequestDto.java
  src/main/java/kr/ssok/ssom/backend/global/dto/LlmApiResponseDto.java
  src/main/java/kr/ssok/ssom/backend/global/dto/LogSummaryMessageDto.java
  src/main/java/kr/ssok/ssom/backend/global/exception/BaseResponseStatus.java
Labels: enhancement

#65 feat: 부서 권한 비굣값 contains 로 수정(#19, SCRUM-212)
  src/main/java/kr/ssok/ssom/backend/domain/alert/controller/AlertController.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertServiceImpl.java
Labels: enhancement

#67 fix: devops endpoint url 변경(#19, SCRUM-212)
  src/main/java/kr/ssok/ssom/backend/domain/alert/controller/AlertController.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertDevopsRequestDto.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertService.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertServiceImpl.java
Labels: bug

#72 fix: deserialize 해결(#30, SCRUM-206)
  src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertDevopsRequestDto.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertGrafanaRequestDto.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertIssueRequestDto.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertModifyRequestDto.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertOpensearchRequestDto.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertRequestDto.java
Labels: bug

#78 chore: devops 알림 생성 디버깅을 위한 로그 수정(#22, SCRUM-207)
  src/main/java/kr/ssok/ssom/backend/domain/alert/controller/AlertController.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertServiceImpl.java
Labels: documentation, duplicate

#79 feat: 실시간 로그 SSE 기능
  src/main/java/kr/ssok/ssom/backend/domain/logging/controller/LoggingController.java
  src/main/java/kr/ssok/ssom/backend/domain/logging/service/Impl/LoggingServiceImpl.java
  src/main/java/kr/ssok/ssom/backend/domain/logging/service/LoggingService.java
  src/main/java/kr/ssok/ssom/backend/domain/logging/sse/EmitterWithFilter.java
Labels: enhancement

#85 fix : issue 관련 timestamp jackson 직렬화 문제해결
  src/main/java/kr/ssok/ssom/backend/global/config/JacksonConfig.java
Labels: bug, enhancement

#87 fix: SSE 비동기 스레드 인증 오류 및 날짜 직렬화 문제 해결
  src/main/java/kr/ssok/ssom/backend/domain/user/security/config/SecurityConfig.java
Labels: bug, enhancement

#88 feat : sse 관련 controller 인증 설정 충돌 해결
  src/main/java/kr/ssok/ssom/backend/domain/alert/controller/AlertController.java
  src/main/java/kr/ssok/ssom/backend/domain/issue/service/Impl/IssueServiceImpl.java
  src/main/java/kr/ssok/ssom/backend/domain/logging/controller/LoggingController.java
  src/main/java/kr/ssok/ssom/backend/domain/user/security/config/SecurityConfig.java
  src/main/java/kr/ssok/ssom/backend/global/exception/BaseResponseStatus.java
Labels: bug, enhancement

#92 feat : SSE의 비동기 콜백 문제로 Spring Security Context 비전파 문제 해결
  src/main/java/kr/ssok/ssom/backend/SsomBackendApplication.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/controller/AlertController.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/exception/SseExceptionHandler.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/scheduler/SseConnectionMonitor.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertService.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertServiceImpl.java
  src/main/java/kr/ssok/ssom/backend/domain/user/security/config/SecurityConfig.java
  src/main/java/kr/ssok/ssom/backend/global/config/WebMvcConfig.java
Labels: bug, enhancement

#93 refactor: Github Issue 발생 시 payload 에 맞게 알림 전송 되도록 변경 (#31, SCRUM-208)
  src/main/java/kr/ssok/ssom/backend/domain/alert/controller/AlertController.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertIssueRequestDto.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertService.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertServiceImpl.java
  src/main/java/kr/ssok/ssom/backend/global/exception/BaseResponseStatus.java
Labels: duplicate, enhancement

#94 fix: 알림 전체 목록 조회 및 읽음 처리시 alertStatusID 주고받도록 처리
  src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertResponseDto.java
Labels: bug

#99 feat: LoginResponseDto 필드 누락 수정
  src/main/java/kr/ssok/ssom/backend/domain/user/controller/UserController.java
  src/main/java/kr/ssok/ssom/backend/domain/user/repository/BiometricInfoRepository.java
  src/main/java/kr/ssok/ssom/backend/domain/user/service/BiometricService.java
  src/main/java/kr/ssok/ssom/backend/domain/user/service/Impl/UserServiceImpl.java
Labels: bug, enhancement

#100 feat: 모든 사용자 목록 조회 API 추가
  src/main/java/kr/ssok/ssom/backend/domain/user/controller/UserController.java
  src/main/java/kr/ssok/ssom/backend/domain/user/dto/UserListResponseDto.java
  src/main/java/kr/ssok/ssom/backend/domain/user/repository/UserRepository.java
  src/main/java/kr/ssok/ssom/backend/domain/user/service/Impl/UserServiceImpl.java
  src/main/java/kr/ssok/ssom/backend/domain/user/service/UserService.java
Labels: enhancement

#101 feat: 생체인증 시스템 보안 및 성능 개선
  src/main/java/kr/ssok/ssom/backend/domain/user/controller/BiometricController.java
  src/main/java/kr/ssok/ssom/backend/domain/user/dto/BiometricLoginRequestDto.java
  src/main/java/kr/ssok/ssom/backend/domain/user/dto/BiometricRegistrationRequestDto.java
  src/main/java/kr/ssok/ssom/backend/domain/user/service/BiometricFailureService.java
  src/main/java/kr/ssok/ssom/backend/domain/user/service/BiometricService.java
  src/main/java/kr/ssok/ssom/backend/domain/user/service/Impl/UserServiceImpl.java
  src/main/java/kr/ssok/ssom/backend/global/exception/BaseResponseStatus.java
Labels: enhancement

#102 fix : 생체인증 상태 확인 본인확인 수정
  src/main/java/kr/ssok/ssom/backend/domain/user/controller/BiometricController.java
Labels: enhancement

#104 merge : develop -> main
  .gitignore
  src/main/java/kr/ssok/ssom/backend/SsomBackendApplication.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/controller/AlertController.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertDevopsRequestDto.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertGrafanaRequestDto.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertIssueRequestDto.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertModifyRequestDto.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertOpensearchRequestDto.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertRequestDto.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertResponseDto.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/entity/Alert.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/exception/SseExceptionHandler.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/scheduler/SseConnectionMonitor.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertService.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertServiceImpl.java
  src/main/java/kr/ssok/ssom/backend/domain/issue/controller/IssueController.java
  src/main/java/kr/ssok/ssom/backend/domain/issue/service/Impl/IssueServiceImpl.java
  src/main/java/kr/ssok/ssom/backend/domain/issue/service/IssueService.java
  src/main/java/kr/ssok/ssom/backend/domain/logging/controller/LoggingController.java
  src/main/java/kr/ssok/ssom/backend/domain/logging/entity/LogSummary.java
  src/main/java/kr/ssok/ssom/backend/domain/logging/entity/Logging.java
  src/main/java/kr/ssok/ssom/backend/domain/logging/repository/LogSummaryRepository.java
  src/main/java/kr/ssok/ssom/backend/domain/logging/repository/LoggingRepository.java
  src/main/java/kr/ssok/ssom/backend/domain/logging/service/Impl/LoggingServiceImpl.java
  src/main/java/kr/ssok/ssom/backend/domain/logging/service/LoggingService.java
  src/main/java/kr/ssok/ssom/backend/domain/logging/sse/EmitterWithFilter.java
  src/main/java/kr/ssok/ssom/backend/domain/user/controller/BiometricController.java
  src/main/java/kr/ssok/ssom/backend/domain/user/controller/UserController.java
  src/main/java/kr/ssok/ssom/backend/domain/user/dto/BiometricLoginRequestDto.java
  src/main/java/kr/ssok/ssom/backend/domain/user/dto/BiometricRegistrationRequestDto.java
  src/main/java/kr/ssok/ssom/backend/domain/user/dto/UserListResponseDto.java
  src/main/java/kr/ssok/ssom/backend/domain/user/repository/BiometricInfoRepository.java
  src/main/java/kr/ssok/ssom/backend/domain/user/repository/UserRepository.java
  src/main/java/kr/ssok/ssom/backend/domain/user/security/config/SecurityConfig.java
  src/main/java/kr/ssok/ssom/backend/domain/user/security/filter/JwtAuthenticationFilter.java
  src/main/java/kr/ssok/ssom/backend/domain/user/security/handler/JwtAuthenticationEntryPoint.java
  src/main/java/kr/ssok/ssom/backend/domain/user/service/BiometricFailureService.java
  src/main/java/kr/ssok/ssom/backend/domain/user/service/BiometricService.java
  src/main/java/kr/ssok/ssom/backend/domain/user/service/Impl/UserServiceImpl.java
  src/main/java/kr/ssok/ssom/backend/domain/user/service/UserService.java
  src/main/java/kr/ssok/ssom/backend/global/config/JacksonConfig.java
  src/main/java/kr/ssok/ssom/backend/global/config/SseConfig.java
  src/main/java/kr/ssok/ssom/backend/global/config/WebMvcConfig.java
  src/main/java/kr/ssok/ssom/backend/global/dto/LogSummaryResponseDto.java
  src/main/java/kr/ssok/ssom/backend/global/exception/BaseResponseStatus.java
Labels: enhancement

#105 test : User domain entity, enum, service 단위테스트 및 webhook url HOTFIX
  src/main/java/kr/ssok/ssom/backend/domain/user/dto/PasswordChangeRequestDto.java
  src/main/java/kr/ssok/ssom/backend/domain/user/security/config/SecurityConfig.java
  src/test/java/kr/ssok/ssom/backend/domain/user/controller/BiometricControllerTest.java
  src/test/java/kr/ssok/ssom/backend/domain/user/entity/AttemptResultTest.java
  src/test/java/kr/ssok/ssom/backend/domain/user/entity/BiometricTypeTest.java
  src/test/java/kr/ssok/ssom/backend/domain/user/entity/DepartmentTest.java
  src/test/java/kr/ssok/ssom/backend/domain/user/entity/UserTest.java
  src/test/java/kr/ssok/ssom/backend/domain/user/service/BiometricServiceTest.java
  src/test/java/kr/ssok/ssom/backend/domain/user/service/UserServiceTest.java
Labels: bug, enhancement

#106 mege : prod 배포 develop -> main
  src/main/java/kr/ssok/ssom/backend/domain/user/dto/PasswordChangeRequestDto.java
  src/main/java/kr/ssok/ssom/backend/domain/user/security/config/SecurityConfig.java
  src/test/java/kr/ssok/ssom/backend/domain/user/controller/BiometricControllerTest.java
  src/test/java/kr/ssok/ssom/backend/domain/user/entity/AttemptResultTest.java
  src/test/java/kr/ssok/ssom/backend/domain/user/entity/BiometricTypeTest.java
  src/test/java/kr/ssok/ssom/backend/domain/user/entity/DepartmentTest.java
  src/test/java/kr/ssok/ssom/backend/domain/user/entity/UserTest.java
  src/test/java/kr/ssok/ssom/backend/domain/user/service/BiometricServiceTest.java
  src/test/java/kr/ssok/ssom/backend/domain/user/service/UserServiceTest.java
Labels: enhancement

#109 hotfix : EKS health check
  src/main/java/kr/ssok/ssom/backend/global/controller/HealthController.java
Labels: enhancement

#112 fix : EKS health check
  src/main/java/kr/ssok/ssom/backend/global/controller/HealthController.java
Labels: bug, enhancement

#113 fix: fcm UserPrincipal 및 alertService Transaction 수정 (#6, SCRUM-209)
  src/main/java/kr/ssok/ssom/backend/domain/alert/controller/fcm/FcmController.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertServiceImpl.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/service/fcm/FcmService.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/service/fcm/FcmServiceImpl.java
Labels: bug

#117 feat: opensearch 알림 리스트 빈 경우 return 처리
  src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertServiceImpl.java
Labels: enhancement

#132 opensearch sse 알림용 url
  src/main/java/kr/ssok/ssom/backend/domain/user/controller/UserController.java
  src/main/java/kr/ssok/ssom/backend/domain/user/security/config/SecurityConfig.java
Labels: enhancement

#139 feat: 알림 알림 실제 발생 시간 최신 순으로 정렬하여 전송 (#6, SCRUM-209)
  src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertDevopsRequestDto.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertRequestDto.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/entity/Alert.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/repository/AlertStatusRepository.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertServiceImpl.java
Labels: enhancement

#141 fix: data type 오류 해결(#6, SCRUM-209)
  src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertResponseDto.java
Labels: bug

#142 merge
  src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertResponseDto.java
Labels: bug

#143 test : BiometricFailureService 개선 및 통합테스트
  src/main/java/kr/ssok/ssom/backend/domain/user/service/BiometricFailureService.java
  src/main/java/kr/ssok/ssom/backend/domain/user/service/Impl/BiometricFailureServiceImpl.java
  src/test/java/kr/ssok/ssom/backend/domain/user/service/BiometricFailureServiceTest.java
Labels: enhancement

#146 fix: datatype String 으로 원복(#6, SCRUM-209)
  src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertDevopsRequestDto.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertRequestDto.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertResponseDto.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/entity/Alert.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertServiceImpl.java
Labels: bug

#150 fix: repository save 누락 오류 해결
  src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertServiceImpl.java
Labels: bug

#153 feat: 이슈 알림 생성 후 Issue status 변경 처리(#31, SCRUM-208)
  src/main/java/kr/ssok/ssom/backend/domain/alert/controller/AlertController.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertIssueRequestDto.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertServiceImpl.java
  src/main/java/kr/ssok/ssom/backend/domain/issue/service/Impl/IssueServiceImpl.java
  src/main/java/kr/ssok/ssom/backend/domain/issue/service/IssueService.java
Labels: enhancement

#155 test: 디버깅 로그 추가(#31, SCRUM-208)
  src/main/java/kr/ssok/ssom/backend/domain/issue/service/Impl/IssueServiceImpl.java
Labels: duplicate

#158 fix: issue service 에서 transactional 제거 (#31, SCRUM-208)
  src/main/java/kr/ssok/ssom/backend/domain/issue/service/Impl/IssueServiceImpl.java
Labels: bug

#162 test: DTO validation 테스트에서 다중 제약조건 검증 로직 수정
  build.gradle
  src/main/java/kr/ssok/ssom/backend/domain/user/security/config/SecurityConfig.java
  src/test/java/kr/ssok/ssom/backend/domain/user/dto/BiometricLoginRequestDtoTest.java
  src/test/java/kr/ssok/ssom/backend/domain/user/dto/BiometricRegistrationRequestDtoTest.java
  src/test/java/kr/ssok/ssom/backend/domain/user/dto/BiometricResponseDtoTest.java
  src/test/java/kr/ssok/ssom/backend/domain/user/dto/BiometricStatusDtoTest.java
  src/test/java/kr/ssok/ssom/backend/domain/user/dto/LoginRequestDtoTest.java
  src/test/java/kr/ssok/ssom/backend/domain/user/dto/LoginResponseDtoTest.java
  src/test/java/kr/ssok/ssom/backend/domain/user/dto/PasswordChangeRequestDtoTest.java
  src/test/java/kr/ssok/ssom/backend/domain/user/dto/SignupRequestDtoTest.java
  src/test/java/kr/ssok/ssom/backend/domain/user/dto/TokenRefreshRequestDtoTest.java
  src/test/java/kr/ssok/ssom/backend/domain/user/dto/UserDtoTestSuite.java
  src/test/java/kr/ssok/ssom/backend/domain/user/dto/UserListResponseDtoTest.java
  src/test/java/kr/ssok/ssom/backend/domain/user/dto/UserRequestDtoTest.java
  src/test/java/kr/ssok/ssom/backend/domain/user/dto/UserResponseDtoTest.java
  src/test/java/kr/ssok/ssom/backend/domain/user/dto/UserSearchResponseDtoTest.java
Labels: enhancement

#164 feat: 전체 Issue 목록 조회 시 OPEN 상태만 반환하도록 수정
  src/main/java/kr/ssok/ssom/backend/domain/issue/service/Impl/IssueServiceImpl.java
Labels: enhancement

#167 feat: 무한스크롤 방식의 로그 조회 기능 추가
  src/main/java/kr/ssok/ssom/backend/domain/logging/controller/LoggingController.java
  src/main/java/kr/ssok/ssom/backend/domain/logging/dto/LogsScrollResponseDto.java
  src/main/java/kr/ssok/ssom/backend/domain/logging/service/Impl/LoggingServiceImpl.java
  src/main/java/kr/ssok/ssom/backend/domain/logging/service/LoggingService.java
Labels: enhancement

#173 feat: SSE 토큰 만료 문제 해결을 위한 전용 장기 토큰 도입
  src/main/java/kr/ssok/ssom/backend/domain/user/dto/LoginResponseDto.java
  src/main/java/kr/ssok/ssom/backend/domain/user/security/filter/JwtAuthenticationFilter.java
  src/main/java/kr/ssok/ssom/backend/domain/user/security/jwt/JwtTokenProvider.java
  src/main/java/kr/ssok/ssom/backend/domain/user/service/Impl/BiometricServiceImpl.java
  src/main/java/kr/ssok/ssom/backend/domain/user/service/Impl/UserServiceImpl.java
Labels: bug, enhancement

#175 feat: Kafka 활용 비동기 처리
  build.gradle
  docker/kafka/docker-compose.kafka.yml
  docs/kafka/README-KAFKA-SETUP.md
  docs/kafka/README-TOPIC-BUILDER.md
  scripts/kafka/create-topics.sh
  scripts/kafka/monitor-topics.sh
  scripts/kafka/setup-permissions.sh
  scripts/kafka/start-kafka.sh
  scripts/kafka/stop-kafka.sh
  src/main/java/kr/ssok/ssom/backend/domain/alert/controller/AlertController.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/dto/kafka/AlertCreatedEvent.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/dto/kafka/UserAlertEvent.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/repository/AlertRepository.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/repository/AlertStatusRepository.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertService.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertServiceImpl.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/service/kafka/AlertKafkaConsumer.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/service/kafka/AlertKafkaProducer.java
  src/main/java/kr/ssok/ssom/backend/global/config/KafkaConfig.java
  src/test/java/kr/ssok/ssom/backend/domain/alert/performance/AlertLoadTest.java
  src/test/java/kr/ssok/ssom/backend/domain/alert/performance/AlertPerformanceTest.java
  src/test/java/kr/ssok/ssom/backend/domain/alert/performance/BasicPerformanceTest.java
  src/test/java/kr/ssok/ssom/backend/domain/alert/performance/PerformanceTestRunner.java
  src/test/java/kr/ssok/ssom/backend/domain/alert/performance/SimpleAlertPerformanceTest.java
  src/test/java/kr/ssok/ssom/backend/domain/user/dto/LoginResponseDtoTest.java
  src/test/java/kr/ssok/ssom/backend/domain/user/dto/UserDtoTestSuite.java
  src/test/java/kr/ssok/ssom/backend/global/config/KafkaConfigTest.java
Labels: enhancement

#177 fix : kafka consumer 역직렬화 문제
  src/main/java/kr/ssok/ssom/backend/domain/alert/service/kafka/AlertKafkaConsumer.java
  src/main/java/kr/ssok/ssom/backend/global/config/KafkaConfig.java
Labels: enhancement

#179 refactor : Kafka 도입 및 비동기 처리 적용 성능 개선 작업
  build.gradle
  docker/kafka/docker-compose.kafka.yml
  docs/kafka/README-KAFKA-SETUP.md
  docs/kafka/README-TOPIC-BUILDER.md
  scripts/kafka/create-topics.sh
  scripts/kafka/monitor-topics.sh
  scripts/kafka/setup-permissions.sh
  scripts/kafka/start-kafka.sh
  scripts/kafka/stop-kafka.sh
  src/main/java/kr/ssok/ssom/backend/domain/alert/controller/AlertController.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/dto/kafka/AlertCreatedEvent.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/dto/kafka/UserAlertEvent.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/repository/AlertRepository.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/repository/AlertStatusRepository.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertService.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertServiceImpl.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/service/kafka/AlertKafkaConsumer.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/service/kafka/AlertKafkaProducer.java
  src/main/java/kr/ssok/ssom/backend/global/config/KafkaConfig.java
  src/test/java/kr/ssok/ssom/backend/domain/alert/performance/AlertLoadTest.java
  src/test/java/kr/ssok/ssom/backend/domain/alert/performance/AlertPerformanceTest.java
  src/test/java/kr/ssok/ssom/backend/domain/alert/performance/BasicPerformanceTest.java
  src/test/java/kr/ssok/ssom/backend/domain/alert/performance/PerformanceTestRunner.java
  src/test/java/kr/ssok/ssom/backend/domain/alert/performance/SimpleAlertPerformanceTest.java
  src/test/java/kr/ssok/ssom/backend/domain/user/dto/LoginResponseDtoTest.java
  src/test/java/kr/ssok/ssom/backend/domain/user/dto/UserDtoTestSuite.java
  src/test/java/kr/ssok/ssom/backend/global/config/KafkaConfigTest.java
Labels: enhancement

#182 fix : 로그 SSE Security Context 충돌 문제 해결
  src/main/java/kr/ssok/ssom/backend/domain/logging/service/Impl/LoggingServiceImpl.java
Labels: bug

#183 merge : prod 배포
  src/main/java/kr/ssok/ssom/backend/domain/alert/README.md
  src/main/java/kr/ssok/ssom/backend/domain/alert/alert_api_spec.md
  src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertServiceImpl.java
  src/main/java/kr/ssok/ssom/backend/domain/logging/service/Impl/LoggingServiceImpl.java
Labels: enhancement

#184 feat: Kafka Consumer 실패 처리 메커니즘 개선
  src/main/java/kr/ssok/ssom/backend/domain/alert/service/kafka/AlertKafkaConsumer.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/service/kafka/AlertKafkaProducer.java
Labels: enhancement

#187 test : 오픈서치 알림 webhook 비동기, 동기 비교 테스트를 위한 푸시알림 부분 주석처리
  src/main/java/kr/ssok/ssom/backend/domain/alert/controller/AlertController.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/controller/AlertPerformanceTestController.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertDevopsRequestDto.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertGrafanaRequestDto.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/repository/AlertRepository.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/repository/AlertStatusRepository.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertPerformanceTestService.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertPerformanceTestServiceImpl.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertServiceImpl.java
  src/main/java/kr/ssok/ssom/backend/domain/user/security/config/SecurityConfig.java
Labels: enhancement

#188 test : 오픈서치 알림 webhook 비동기, 동기 비교 테스트를 위한 푸시알림 부분 주석처리
  src/main/java/kr/ssok/ssom/backend/domain/alert/controller/AlertController.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/controller/AlertPerformanceTestController.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertDevopsRequestDto.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertGrafanaRequestDto.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/repository/AlertRepository.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/repository/AlertStatusRepository.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertPerformanceTestService.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertPerformanceTestServiceImpl.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertServiceImpl.java
  src/main/java/kr/ssok/ssom/backend/domain/user/security/config/SecurityConfig.java
Labels: enhancement

#190 test : countByCreatedAtAfter 안쓰는 JPA 메서드 삭제
  src/main/java/kr/ssok/ssom/backend/domain/alert/repository/AlertRepository.java
  src/main/java/kr/ssok/ssom/backend/domain/alert/repository/AlertStatusRepository.java
Labels: bug
